CREATE TABLE Message
(
  	id SERIAL NOT NULL,
  	pair VARCHAR(15),
	market VARCHAR(15),
	price DOUBLE PRECISION,
	best_ask DOUBLE PRECISION,
	best_bid DOUBLE PRECISION,
	time BIGINT,
  	PRIMARY KEY (id)
)
